package com.spring.entity;
// Generated 22.Ağu.2020 12:15:05 by Hibernate Tools 4.3.1



import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;



/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
    ,catalog="webshopping"
)
public class Product  implements java.io.Serializable {


     private long productId;
     private Brand brand;
     private Category category;
     private String productName;
     private String paroductDescription;
     private BigDecimal productPrice;
     private Date productRegister;
     private short status;
     private String productImagepath;

    public Product() {
    }

    public Product(long productId, Brand brand, Category category, String productName, String paroductDescription, BigDecimal productPrice, Date productRegister, short status, String productImagepath) {
       this.productId = productId;
       this.brand = brand;
       this.category = category;
       this.productName = productName;
       this.paroductDescription = paroductDescription;
       this.productPrice = productPrice;
       this.productRegister = productRegister;
       this.status = status;
       this.productImagepath = productImagepath;
    }
   
     @Id
@GeneratedValue(strategy = GenerationType.IDENTITY)

    
    @Column(name="product_id", unique=true, nullable=false)
    public long getProductId() {
        return this.productId;
    }
    
    public void setProductId(long productId) {
        this.productId = productId;
    }

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name="brand_id", nullable=false)
    public Brand getBrand() {
        return this.brand;
    }
    
    public void setBrand(Brand brand) {
        this.brand = brand;
    }

	@ManyToOne(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinColumn(name="category_id", nullable=false)
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="product_name", nullable=false, length=50)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="paroduct_description", nullable=false, length=50)
    public String getParoductDescription() {
        return this.paroductDescription;
    }
    
    public void setParoductDescription(String paroductDescription) {
        this.paroductDescription = paroductDescription;
    }

    
    @Column(name="product_price", nullable=false, precision=6)
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="product_register", nullable=false, length=10)
    public Date getProductRegister() {
        return this.productRegister;
    }
    
    public void setProductRegister(Date productRegister) {
        this.productRegister = productRegister;
    }

    
    @Column(name="status", nullable=false)
    public short getStatus() {
        return this.status;
    }
    
    public void setStatus(short status) {
        this.status = status;
    }

    
    @Column(name="product_imagepath", nullable=false, length=200)
    public String getProductImagepath() {
        return this.productImagepath;
    }
    
    public void setProductImagepath(String productImagepath) {
        this.productImagepath = productImagepath;
    }




}


